name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Adjusted to use your self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Restart Application
      run: |
        echo "Restarting application..."
        pm2 restart app || pm2 start npm --name "app" -- run dev
        pm2 save
        echo "Deployment completed!"
