name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ec2-user
      run: |
        echo "$PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        echo "Connecting to EC2 instance..."
        
        ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
          echo "Connected to EC2"

          cd /home/ec2-user || exit

          if [ ! -d "dark-mode-legacy" ]; then
            echo "Cloning repository..."
            git clone git@github.com:AliIshaqPro/dark-mode-legacy.git dark-mode-legacy
          fi

          cd dark-mode-legacy || exit
          
          echo "Fetching latest code..."
          git fetch --all
          git reset --hard origin/main
          git pull origin main

          echo "Installing dependencies..."
          npm ci
          
          echo "Building project..."
          npm run build
          
          echo "Restarting application..."
          pm2 restart app || pm2 start npm --name "app" -- run dev
          pm2 save
          
          echo "Deployment completed!"
        EOF
